from abc import ABC, abstractmethod

class BaseEnvironment(ABC):
    """
    Abstract base class for all `verl` environments in `sudo-SQL`.
    """

    @abstractmethod
    def __init__(self, **kwargs):
        """
        Initializes the environment.
        """
        pass

    @abstractmethod
    def step(self, generated_sql: str) -> tuple[str, float]:
        """
        Executes a step in the environment.

        Args:
            generated_sql: The SQL query generated by the model.

        Returns:
            A tuple containing the observation (e.g., query result or error) and the reward.
        """
        pass