# configs/models.yaml

openai_gpt4:
  type: "openai"
  args:
    model: "gpt-4"
    # api_key can be set here or via environment variable OPENAI_API_KEY

openai_gpt3_5:
  type: "openai"
  args:
    model: "gpt-3.5-turbo"

huggingface_t5:
  type: "huggingface"
  args:
    model_name: "t5-small"